name: CI
on: [push, pull_request]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Dub Test
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
        dc:
          - dmd-2.099.0
        arch:
          - x86_64
        clang:
          - 12.0.0
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
          bundler-cache: true
      # Ruby puts this on the path which breaks ldc
      - name: Rename msys64/link.exe
        if: startsWith(matrix.os,'windows')
        shell: pwsh
        run: mv C:\msys64\usr\bin\link.exe C:\msys64\usr\bin\msys-link.exe

      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/llvm
          key: cache-os:${{ matrix.os }}-clang:${{ matrix.clang }}

      - name: Setup D
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Setup C++
        uses: aminya/setup-cpp@v1
        with:
          llvm: ${{ matrix.clang }}

      - name: print cpp info
        run: |
          if [ -x "$(which clang-cpp 2> /dev/null)" ]; then
            cpp_bin=$(which clang-cpp)
          else
            cpp_bin=$(which cpp)
          fi
          echo "cpp path: $cpp_bin"
          $cpp_bin --version

      - name: Run tests
        run: |
          dub run -q -- --ignore-system-paths --preprocess-only issue.dpp
          echo "==="
          cat issue.d
          echo "==="
          dmd -run issue.d
        env:
          LIBRARY_PATH: "${{ env.LLVM_PATH }}/lib"

  test-with-default-env:
    name: Dub Test on macOS
    strategy:
      matrix:
        os: [macos-10.15]
        dc:
          - dmd-2.099.0
        arch:
          - x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
          bundler-cache: true

      - name: Setup D
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: print cpp info
        run: |
          if [ -x "$(which clang-cpp 2> /dev/null)" ]; then
            cpp_bin=$(which clang-cpp)
          else
            cpp_bin=$(which cpp)
          fi
          echo "cpp path: $cpp_bin"
          $cpp_bin --version

      - name: Run tests
        run: |
          dub run -q -- --ignore-system-paths --preprocess-only issue.dpp
          echo "==="
          cat issue.d
          echo "==="
          dmd -run issue.d
