name: CI
on: [push, pull_request]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Dub Test
    strategy:
      fail-fast: false
      matrix:
        os:
          # - ubuntu-20.04
          # - windows-2019
          - macos-10.15
          - macos-latest
        dc:
          # - dmd-2.099.0
          - ldc-1.28.1
        arch:
          - x86_64
        clang:
          - 12.0.0
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
          bundler-cache: true
      # Ruby puts this on the path which breaks ldc
      - name: Rename msys64/link.exe
        if: startsWith(matrix.os,'windows')
        shell: pwsh
        run: mv C:\msys64\usr\bin\link.exe C:\msys64\usr\bin\msys-link.exe

      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/llvm
          key: cache-os:${{ matrix.os }}-clang:${{ matrix.clang }}

      - name: Setup D
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Setup C++
        uses: aminya/setup-cpp@v1
        with:
          llvm: ${{ matrix.clang }}

      - name: test cpp
        run: |
          cpp --version
          clang -v -xc++ /dev/null -fsyntax-only
      - name: check headers
        run: |
          echo "======"
          ls /Users/runner/hostedtoolcache/llvm/12.0.0/x64/bin/../include/c++/v1/stddef.h
          grep "include_next" /Users/runner/hostedtoolcache/llvm/12.0.0/x64/bin/../include/c++/v1/stddef.h
          echo "======"
          cat /Users/runner/hostedtoolcache/llvm/12.0.0/x64/bin/../include/c++/v1/stddef.h
          cp /Users/runner/hostedtoolcache/llvm/12.0.0/x64/bin/../include/c++/v1/stddef.h stddef.h
      - uses: actions/upload-artifact@v3
        with:
          name: stddef.h
          path: stddef.h
      - run: |
          dub run -- --keep-pre-cpp-files --keep-d-files --compiler=ldc2 issue400.dpp
          echo "======="
          cat issue400.d.tmp
          echo "======="
          cpp -w --comments issue400.d.tmp
      - uses: actions/upload-artifact@v3
        with:
          name: issue400.d.tmp
          path: issue400.d.tmp


      # - name: Run tests
      #   continue-on-error: ${{ contains(matrix.os, 'macos') }}
      #   run: dub test -q --build=unittest-cov --arch=${{ matrix.arch }} -- @issue
      #   env:
      #     LIBRARY_PATH: "${{ env.LLVM_PATH }}/lib"

      # - name: Build binary
      #   run: dub build -q --arch=${{ matrix.arch }}
      #   env:
      #     LIBRARY_PATH: "${{ env.LLVM_PATH }}/lib"

      # - uses: codecov/codecov-action@v1
